[package]
name = "sonic-number-simd"
version = "0.1.0"
edition = "2024"

[dependencies]
atoi_simd = "0.18.1"

[dev-dependencies]
rand = "0.8"
criterion = "0.6"

[[bench]]
harness = false
name    = "atoi"